#:kivy 2.2.1

<Header>:
    canvas.before:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size
<RoundedButton@Button>:
	background_color: (0,0,0,0)
	background_normal: ''
    padding: 10
	canvas.before:
		Color:
			rgba: (217/255,217/255,217/255,1)
		RoundedRectangle:
			size: self.size
			pos: self.pos
			radius: [8]
<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'
    angle: 90

<CrackContainer1>:
    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        size: root.width, self.height

        RelativeLayout:  # Sử dụng RelativeLayout để định vị logo và label
            size_hint_y: None
            height: dp(100)
            Header:
                top: root.top
                size: root.width, self.height
                RelativeLayout:
                    orientation: 'horizontal'
                    size_hint: None, None
                    size: dp(430), dp(100)  # Điều chỉnh kích thước của phần logo và label
                    valign: 'middle'
                    canvas.before:
                        Color:
                            rgba: (19/255, 98/255, 197/255, 1)  # Màu xanh dương
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Image:
                        size_hint_x: None
                        width: dp(80)
                        pos_hint: {'center_x': 0.2, 'center_y': 0.5}
                        center_y: self.parent.center_y
                        source: 'logo.png'
                        valign: 'middle'
                    Label:
                        font_size: 55
                        pos_hint: {'center_x': 0.6, 'center_y': 0.5}
                        text: "AIOT LAB VN"
                        color: 1, 1, 1, 1
                        bold: True
                        valign: 'middle'

        RelativeLayout:
            orientation:'vertical'            
            size: root.width, 700
           
            Label:
                pos_hint: {"center_x":0.5, "center_y":0.97}
                font_size: 30
                size_hint: None, None 
                text: "CRACK INSPECTOR 360"
                color: 19/255, 98/255, 197/255, 1
                size: root.width, 30
                text_size: self.size
                halign: 'center'
                valign: 'top'
                padding: 10, 0
                bold: True

            Label:
                pos_hint: {"center_x":0.5, "center_y":0.87}
                text: "Quickly evaluate the location and extent of cracks, an algorithm built on the YOLOv8 platform to detect and evaluate different levels of cracks in images. Developed by students of CE and IT departments of international universities."
                size_hint_y: None 
                font_size: 20
                color: 0, 0, 0, 1
                size: root.width, 30
                height: self.texture_size[1]
                text_size: self.width, None
                halign: 'center'
                padding: 10, 0
            
            Label:
                pos_hint: {"center_x":0.5, "center_y":0.75}
                font_size: 30
                size_hint: None, None # Shrink the label size to the text size
                text: "ABOUT US"
                color: 19/255, 98/255, 197/255, 1
                size: root.width, 30
                halign: 'center'
                text_size: self.size
                bold: True

            Label:
                pos_hint: {"center_x":0.5, "center_y":0.7}
                text: "AIoT Lab VN, established in 2022, is a pioneering hub at the forefront of Artificial Intelligence and Internet of Things in Vietnam."
                size_hint_y: None # Shrink the label size to the text size
                font_size: 20
                color: 0, 0, 0, 1
                size: root.width, 30
                height: self.texture_size[1]
                text_size: self.width, None
                halign: 'center'
                padding: 10, 0

            OpenCamera:
                id: camera
                play: False
                opacity: 0

            RoundedButton:
                id: open_cam
                pos_hint: {"center_x":0.5, "center_y":0.6}
                text: 'GET STARTED'
                on_press:
                    self.opacity = 0.5
                on_release:
                    self.opacity = 1
                    app.root.get_screen("second").ids.camera.play = True
                    app.root.current = 'second'
                size_hint: None, None
                size: dp(142), dp(48)
                color: 1, 1, 1, 1
                background_color: 19/255, 98/255, 197/255, 1


#<CrackContainer2>:
    #name: "second"
    #close_cam: close_cam
    #start_cam: start_cam
    #detect_img: detect_img
    #report: report

