#:kivy 2.2.1

<RoundedButton@Button>:
	background_color: (0,0,0,0)
	background_normal: ''
    padding: 10
	canvas.before:
		Color:
			rgba: (217/255,217/255,217/255,1)
		RoundedRectangle:
			size: self.size
			pos: self.pos
			radius: [8]

<Header>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.65
        BoxShadow:
            pos: self.pos
            size: root.width, dp(80)
            offset: 0, -10
            blur_radius: 35
            spread_radius: -10, -10

    canvas:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: root.width, dp(80)

<OpenCamera>:
    resolution: (480, 360)
    play: False
    #keep_ratio: True
    pos_hint:{"x":-0.3, "top":0.96}


#ScreenManager:
    #CrackContainer1:
    #CrackContainer2:

<CrackContainer1>:
    name: "first"
    open_cam: open_cam

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size

    # Header:
    #     top: root.top
    #     size: root.width, dp(80)

    RelativeLayout:
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, self.height


        Image:
            top: root.top
            size_hint_y: None
            height: dp(67)
            #center_x: root.width / 2
            source: 'logo.png'

        Label:
            top: root.top - 120
            font_size: 24
            text: "CRACK DETECTION APP"
            color: 0, 0, 0, 1
            size_hint: None, None # Shrink the label size to the text size
            size: root.width, 30
            text_size: self.size
            halign: 'left'
            valign: 'top'
            padding: 10, 0


        OpenCamera:
            id: camera
            play: False
            opacity: 0


        RoundedButton:
            id: open_cam
            top: root.top - 180
            text: 'Open Camera'
            on_press:
                self.opacity = 0.5
                #camera.play = not camera.play
            on_release:
                app.root.get_screen("second").ids.camera.play = True
                app.root.current = 'second'
                self.opacity = 1


            size_hint: None, None
            size: dp(142), dp(48)
            color: 0, 0, 0, 1
            pos: root.x + 10, self.y



<CrackContainer2>:
    name: "second"
    close_cam: close_cam
    start_cam: start_cam

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size


    RelativeLayout:
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, self.height

        Image:
            top: root.top
            size_hint_y: None
            height: dp(67)
            #center_x: root.width / 2
            source: 'logo.png'

        Label:
            top: root.top - 120
            font_size: 24
            text: "CRACK DETECTION APP"
            color: 0, 0, 0, 1
            size_hint: None, None # Shrink the label size to the text size
            size: root.width, 30
            text_size: self.size
            halign: 'left'
            valign: 'top'
            padding: 10, 0

        OpenCamera:
            id: camera
            play: True

        #Close Button
        RoundedButton:
            canvas.before:
                Color:
                    rgba: (255/255, 102/255, 102/255, 1) #Red
                RoundedRectangle:
			        size: self.size
			        pos: self.pos
            radius: 15
            id: close_cam
            top: root.top - 180
            text: 'Close camera'
            bold: True
            on_press:
                self.opacity = 0.5
            on_release:
                camera.play = False
                self.opacity = 1
                root.manager.current = 'first'
            size_hint: None, None
            size: dp(142), dp(48)
            color: 1, 1, 1, 1
            pos: root.x + 10, self.y

        RoundedButton:
            canvas.before:
                Color:
                    rgba: (102/255, 178/255, 255/255, 1) #Blue
                RoundedRectangle:
			        size: self.size
			        pos: self.pos
            radius: 15
            id: start_cam
            top: root.top - 700
            text: 'Capture Image'
            bold: True
            on_press: self.opacity = 0.5
            on_release:
                self.opacity = 1
                root.capture()
            size_hint: None, None
            size: dp(142), dp(48)
            color: 1, 1, 1, 1
            pos: root.x + 10, self.y


