name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cd to project
        run: |
          ls && cd reactapp
  install-and-test:
    needs: pre
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd reactapp && npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd reactapp && npm install
      - name: Build Android Release
        run: |
          cd reactapp && cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/